// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace UnimindAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Competicao", b =>
                {
                    b.Property<int>("IdCompeticao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idCompeticao");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCompeticao"));

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date")
                        .HasColumnName("data");

                    b.Property<int>("IdNivel")
                        .HasColumnType("integer")
                        .HasColumnName("idNivel");

                    b.Property<int>("IdUsuario1")
                        .HasColumnType("integer")
                        .HasColumnName("idUsuario1");

                    b.Property<int>("IdUsuario2")
                        .HasColumnType("integer")
                        .HasColumnName("idUsuario2");

                    b.HasKey("IdCompeticao");

                    b.ToTable("Competicao", "unimind");
                });

            modelBuilder.Entity("Flashcard", b =>
                {
                    b.Property<int>("IdFlashcard")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idFlashcard");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdFlashcard"));

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("idUsuario");

                    b.Property<string>("PerguntaUsuario")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("perguntaUsuario");

                    b.Property<string>("RespostaUsuario")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("respostaUsuario");

                    b.HasKey("IdFlashcard");

                    b.ToTable("Flashcard", "unimind");
                });

            modelBuilder.Entity("ListaPersonalizada", b =>
                {
                    b.Property<int>("IdLista")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idLista");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdLista"));

                    b.Property<int?>("Ano")
                        .HasColumnType("integer")
                        .HasColumnName("ano");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("integer")
                        .HasColumnName("idCategoria");

                    b.Property<int?>("IdFonte")
                        .HasColumnType("integer")
                        .HasColumnName("idFonte");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("idUsuario");

                    b.HasKey("IdLista");

                    b.ToTable("ListaPersonalizada", "unimind");
                });

            modelBuilder.Entity("Prova", b =>
                {
                    b.Property<int>("IdProva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idProva");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdProva"));

                    b.Property<int>("Ano")
                        .HasColumnType("integer")
                        .HasColumnName("ano");

                    b.Property<string>("Fase")
                        .HasColumnType("text")
                        .HasColumnName("fase");

                    b.Property<int>("IdFonte")
                        .HasColumnType("integer")
                        .HasColumnName("idFonte");

                    b.Property<int>("QntdQuestoes")
                        .HasColumnType("integer")
                        .HasColumnName("qntdQuestoes");

                    b.HasKey("IdProva");

                    b.ToTable("Prova", "unimind");
                });

            modelBuilder.Entity("Questao", b =>
                {
                    b.Property<int>("IdQuestao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idQuestao");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdQuestao"));

                    b.Property<int>("IdCategoria")
                        .HasColumnType("integer")
                        .HasColumnName("idCategoria");

                    b.Property<int>("IdProva")
                        .HasColumnType("integer")
                        .HasColumnName("idProva");

                    b.Property<string>("Pergunta")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("questao");

                    b.Property<string>("Resposta")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("resposta");

                    b.HasKey("IdQuestao");

                    b.ToTable("Questao", "unimind");
                });

            modelBuilder.Entity("Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idUsuario");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUsuario"));

                    b.Property<int?>("AcertosQuestoes")
                        .HasColumnType("integer")
                        .HasColumnName("acertosQuestoes");

                    b.Property<int?>("CompeticoesRealizadas")
                        .HasColumnType("integer")
                        .HasColumnName("competicoesRealizadas");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<int?>("ErrosQuestoes")
                        .HasColumnType("integer")
                        .HasColumnName("errosQuestoes");

                    b.Property<int?>("IdNivel")
                        .HasColumnType("integer")
                        .HasColumnName("idNivel");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("senha");

                    b.Property<int?>("TempoEstudo")
                        .HasColumnType("integer")
                        .HasColumnName("tempoEstudo");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuario", "unimind");
                });
#pragma warning restore 612, 618
        }
    }
}
